name: vsjfirebase
description: A Firebase Flutter Project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.8.3
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

